---
# tasks file for solana
- name: Installing packages
  package:
    name: "{{ packages }}"
    state: present
  changed_when: false
    
- name: Install solana-cli
  shell: sh -c "$(curl -sSfL {{ solana_install_url }})"
  become: true
  changed_when: false

- name: mv solana-cli to /usr/bin
  copy:
    remote_src: yes
    src: '{{ solana_bin_path }}/solana'
    dest: /usr/bin/solana
    mode: 0755
  become: true
  changed_when: false

- name: Get the solana-cli version 
  command: solana --version
  register: check_solana
  changed_when: false

- name: Display solana-cli version
  debug:
    msg: '{{ check_solana.stdout_lines }}'
  changed_when: false
